### ISSUE TITLE
Current Mac version broken

### ISSUE THREAD

**Issue by tarasis** [arjunacharya10/thinker#4]
I am unable to open the Mac version I downloaded yesterday. macOS says its broken and offers to move it to the bin.

**Comment by arjunacharya10** [comment]
Did you download it form here? https://arjunchangeeachary.wixsite.com/thinker ? Also what version of mac are you using and if you can provide the screenshot of the error thrown that would be helpful. In the mean time let me try recreating the issue.

**Comment by arjunacharya10** [comment]
> I am unable to open the Mac version I downloaded yesterday. macOS says its broken and offers to move it to the bin.

I was able to recreate the issue in my system. I have fixed and uploaded the new file here: https://arjunchangeeachary.wixsite.com/thinker . Please let me know if this fixed the isse.

**Comment by tarasis** [comment]
Hi, still an issue. Just redownloaded it and yes, I got it from your wixsite. Note while the date on GDrive was today, the .app was still dated April 4th.

![Uploading Screenshot 2024-04-06 at 11.17.03.png…]()

**Comment by arjunacharya10** [comment]
Interesting. The only thing I did was Zip the Application I use in my system and upload it. When I download the zip and try to run, it is throwing the same error. https://youtu.be/ZH8_XHzkKD4?si=omNgaTwfa6sieclh seems to make it work but still dont know what the core issue is. Please let me know if you have any expertise in this. However the youtube tutorial makes it work.

**Comment by arjunacharya10** [comment]
Basically: First move the .app into the Applications folder.

1. Run in terminal:  `sudo spctl --master-disable`
2. Run in Terminal: `xattr -cr /Applications/Thinker.app`
3. Open thinker
4. Run in terminal: `sudo spctl --master-enable` to enable the security again

Please let me know if this works

**Comment by tarasis** [comment]
Cheers for the steps. Now have it running.

Just as an aside, there is a script that also does those steps.

https://github.com/wynioux/macOS-GateKeeper-Helper

 - Download
 - `chmod +x GateKeeper_Helper.command`
 - Double Click it
 - Selection option 5 to self sign
 - Drag app onto terminal window
 - Press return
 - Now for the first time, right click on the app and select open. Confirm you are sure.
 
Leaves you the benefit of not having to remember to disable/re-enable Gatekeeper.
